version: "3.9"

services:
  multitool:
    build: .
    depends_on:
      - dvwa
      - redis
      - worker
    command: pytest

  dvwa:
    image: vulnerables/web-dvwa:1.9

  worker:
    build: .
    entrypoint: celery
    command: -q -A modules.task_queue worker -E
    depends_on:
      - redis

  redis:
    image: redis:7.0.11
