version: "3.9"

services:
  multitool:
    build: .
    container_name: multitool
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - dvwa
      - redis
    env_file:
      - .env
    command: python main.py

  dvwa:
    image: vulnerables/web-dvwa:1.9
    container_name: dvwa
    ports:
      - "80:80"


  redis:
    restart: unless-stopped
    image: redis:7.0.11
    ports:
      - ${REDIS_EXPOSE_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
