version: "3.9"

services:
  multitool:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - dvwa
      - redis
    env_file:
      - .env
    command: python main.py

  dvwa:
    image: vulnerables/web-dvwa:1.9

  worker:
    restart: unless-stopped
    build: .
    entrypoint: celery
    command: -q -A modules.task_queue worker -l info -E
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      PYTHONPATH: /app

  flower:
    build: .
    image: mher/flower:2.0
    command: celery -A modules.task_queue flower
    working_dir: /app
    ports:
      - "5555:5555"
    depends_on:
      - worker
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis

  redis:
    restart: unless-stopped
    image: redis:7.0.11
