version: "3.9"

services:
  test-multitool:
    build: .
    depends_on:
      - test-dvwa
      - redis
      - test-worker
    command: pytest
    env_file:
      - .env
    volumes:
      - type: bind
        source: /
        target: /project/

  test-dvwa:
    image: vulnerables/web-dvwa:1.9

  test-worker:
    build: .
    entrypoint: celery
    command: -A modules.task_queue.celery -b "redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}" --result-backend "redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}" worker
    depends_on:
      - redis

  redis:
    image: cimg/redis:7.0.11
