version: "3.9"

services:
  multitool:
    build: .
    depends_on:
      - dvwa
      - redis
      - worker
    command: pytest
    env_file:
      - .env

  dvwa:
    image: vulnerables/web-dvwa:1.9

  worker:
    build: .
    entrypoint: celery
    command: -A modules.task_queue.celery -b "redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}" --result-backend "redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}" worker
    depends_on:
      - redis

  redis:
    image: cimg/redis:7.0.11
