version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  integration-tests:
    executor:
      name: docker/docker
    steps:
      - checkout
      - docker/install-docker-tools
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: "Build Docker containers"
          command: |
            docker-compose -f "docker-compose.tests.yaml" build
      - run:
          name: "Start containers"
          command: |
            docker-compose -f "docker-compose.tests.yaml" up dvwa redis worker -d
      - run:
          name: "Wait for DVWA to start"
          command: |
            sleep 10
      - run:
          name: "Run tests"
          command: |
            docker-compose -f "docker-compose.tests.yaml" up multitool


workflows:
  multitool-tests:
    jobs:
      - integration-tests
