name: Multitool Docker Compose Testing Environment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Compose
          run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

        - name: Build and run Docker Compose
          run: |
            docker compose -f ./docker-compose.tests.yaml up dvwa worker redis -d

        - name: Run integration tests
          run: |
            docker compose -f ./docker-compose.tests.yaml  up multitool -d
#            docker exec -it your_app_container_name pytest

        - name: Stop and remove containers
          run: |
            docker compose down --volumes
