name: Multitool Docker Compose Testing Environment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Compose
          run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

        - name: Build and run Docker Compose
          continue-on-error: true
          env:
            CELERY_LOG_LEVEL: "INFO"
            CELERY_BROKER_URL: "redis://redis"
            CELERY_RESULT_BACKEND: "redis://redis"
            CELERY_FLOWER_PORT: "5555"
            CELERY_FLOWER_EXPOSED_PORT: "5555"

          run: |
            docker compose -f ./docker-compose.tests.yaml up -d

        - name: Run unit tests
          run: |
            docker exec multitool-multitool-1 pytest tests/unit/

        - name: Run integration tests
          continue-on-error: true
          env:
            CELERY_LOG_LEVEL: "INFO"
            CELERY_BROKER_URL: "redis://redis"
            CELERY_RESULT_BACKEND: "redis://redis"
            CELERY_FLOWER_PORT: "5555"
            CELERY_FLOWER_EXPOSED_PORT: "5555"
          run: |
            docker exec multitool-multitool-1 pytest tests/integration/

        - name: Stop and remove containers
          env:
            CELERY_LOG_LEVEL: "INFO"
            CELERY_BROKER_URL: "redis://redis"
            CELERY_RESULT_BACKEND: "redis://redis"
            CELERY_FLOWER_PORT: "5555"
            CELERY_FLOWER_EXPOSED_PORT: "5555"
          run: |
            docker compose -f ./docker-compose.tests.yaml down --volumes
