name: Multitool Docker Compose Testing Environment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.tests.yaml"
          down-flags: "--volumes"
          test-container: "multitool"
          test-command: "pytest"

#          compose-file: "./docker-compose.tests.yaml"
#          down-flags: "--volumes"
#          services: |
#          command:
